# -*- coding: utf-8 -*-
"""
Django settings for aplicacion project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+s!7-bs!e#l)gwm#2ckpbq=(%4v%4qx=am-*q+1km3hjbs8nad'

# SECURITY WARNING: don't run with debug turned on in production!
#<<<<<<< HEAD
DEBUG = True
TEMPLATE_DEBUG = DEBUG
ALLOWED_HOSTS = ['humberto.pythonanywhere.com']
#ALLOWED_HOSTS = []

#>>>>>>> d9c1d0b5d486a68905c8dfe590338b2f2372e74d

AUTH_USER_MODEL = 'accounts.Users'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'datos',
    'accounts',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aplicacion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aplicacion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_school',
        'USER': 'root',
        'PASSWORD': '',
    }
}

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'humberto$default',
        'USER': 'humberto',
        'PASSWORD': '01051998a.',
        'HOST':'humberto.mysql.pythonanywhere-services.com',
    }
}

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd5tdl855gn3k0v',
        'USER': 'zgxrtwkxnxzgrm',
        'PASSWORD': 'cdebf1179a4be757d4e40113dd997bc0694d4780601a850b3acd155a5dd25a7a',
        'HOST': 'ec2-54-163-230-219.compute-1.amazonaws.com',
        'PORT': 5432,
    }
}
"""


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Caracas'

FORMAT_MODULE_PATH  = 'config.formats'
USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR), 'static'
]


LOGIN_REDIRECT_URL = reverse_lazy('dato:app_inicio')
LOGOUT_REDIRECT_URL = reverse_lazy('login')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Recupear contraseña Usuarios
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'humbertoanduezaa@gmail.com'
EMAIL_HOST_PASSWORD = '01051998a'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#SESSION EXPIRED
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 120 # set just 10 seconds to test
SESSION_SAVE_EVERY_REQUEST = True
#HTTPS
SECURE_SSL_REDIRECT = True