# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estatus',
            field=models.CharField(choices=[('0', 'Aprobado'), ('1', 'Reprobado'), ('2', 'Finalizado')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
