# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ing_famil',
            field=models.CharField(max_length=9),
        ),
    ]
