# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asigna_materia',
            name='fecha',
        ),
    ]
