# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2011-05-06 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='estatus',
        ),
    ]
