# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2011-05-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asigna_materia',
            name='materia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datos.Materia'),
        ),
        migrations.AlterField(
            model_name='asigna_materia',
            name='profesor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datos.Profesor'),
        ),
    ]
