# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2011-05-06 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_remove_notificacion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estatus',
            field=models.NullBooleanField(),
        ),
    ]
