# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_auto_20180314_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='id_nivel',
        ),
        migrations.AddField(
            model_name='asigna_materia',
            name='id_nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datos.Nivel'),
            preserve_default=False,
        ),
    ]
