# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_auto_20180314_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='asigna_materia',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
    ]
