# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_auto_20180207_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estatus',
            field=models.CharField(blank=True, choices=[('0', 'Aprobado'), ('1', 'Reprobado')], max_length=20),
        ),
    ]
