# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2011-05-06 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_notificacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='hora',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
