# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0005_inscripcion_retirado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='iglesia',
            field=models.CharField(choices=[('', 'Iglesias'), ('Bet-el Mijagualito', 'Bet-el Mijagualito'), ('Bet-el Desembocadero', 'Bet-el Desembocadero'), ('Bet-el Mesa del Cacao', 'Bet-el Mesa del Cacao'), ('Bet-el Patriciera', 'Bet-el Patriciera'), ('Bet-el Marfilar', 'Bet-el Marfilar'), ('Bet-el Santa Elena', 'Bet-el Santa Elena'), ('Bet-el Barrancones', 'Bet-el Barrancones'), ('Bet-el Los Playones', 'Bet-el Los Playones'), ('Bet-el Guerrilandia', 'Bet-el Guerrilandia'), ('Bet-el Papelon', 'Bet-el Papelon'), ('Bet-el Biscucuy', 'Bet-el Biscucuy'), ('Bet-el Bucaral', 'Bet-el Bucaral'), ('Bet-el El muji', 'Bet-el El muji'), ('Bet-el Barro Negro', 'Bet-el Barro Negro'), ('Bet-el Morichal', 'Bet-el Morichal')], max_length=60),
        ),
    ]
